// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRi55wXF4kMZsvieArvnUTwdAFoMMtMA',
    appId: '1:810984231490:web:4d63907ab789add58c13db',
    messagingSenderId: '810984231490',
    projectId: 'admin-page-a8ba0',
    authDomain: 'admin-page-a8ba0.firebaseapp.com',
    storageBucket: 'admin-page-a8ba0.appspot.com',
    measurementId: 'G-SWKRG2WSLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGtncREf_yQsZG4NW7maCyMFNdPondmHw',
    appId: '1:810984231490:android:229a581aa7280ec68c13db',
    messagingSenderId: '810984231490',
    projectId: 'admin-page-a8ba0',
    storageBucket: 'admin-page-a8ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA8FRyBQmT_qIujaXBYQYdE1grTwku9h4',
    appId: '1:810984231490:ios:974b8c1c60c03a208c13db',
    messagingSenderId: '810984231490',
    projectId: 'admin-page-a8ba0',
    storageBucket: 'admin-page-a8ba0.appspot.com',
    iosClientId: '810984231490-83ev4k2kdi7p8vif55dutfh70ukeg9t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA8FRyBQmT_qIujaXBYQYdE1grTwku9h4',
    appId: '1:810984231490:ios:974b8c1c60c03a208c13db',
    messagingSenderId: '810984231490',
    projectId: 'admin-page-a8ba0',
    storageBucket: 'admin-page-a8ba0.appspot.com',
    iosClientId: '810984231490-83ev4k2kdi7p8vif55dutfh70ukeg9t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPage',
  );
}
